# The new backend will not work unless you bravely opt in to experimental features
run.experimental_features_enabled = true

# Set the default backend to LSF + Apptainer
run.backends.default.type = "lsf_apptainer"

# This parameter is optional. If it's absent, jobs will be submitted to your LSF cluster's default
# queue.
run.backends.default.queue = "standard"

# The maximum number of subtasks each `scatter` will try executing at once. This is *not* a direct
# limit on the total number of concurrent tasks, but can affect the number of jobs that get queued
# at one time.
run.backends.default.max_scatter_concurrency = 100

# The directory where `.sif` images will be cached. Be sure to regularly clear this out.
run.backends.default.apptainer_images_dir = "~/.cache/sprocket-apptainer-images"